gui:
  main:
    size: 36
  range:
    size: 9

guiitem:
  maingui:
    itemone:
      type: rangeselector
      name: '&bRange Selector'
      material: COMPASS
      lore:
        - ''
        - ''
        - ''
      invslot: 13
    itemtwo:
      type: biome
      name: '&2&lForest Biome'
      material: LOG
      lore:
        - ''
        - ''
        - ''
      invslot: 33
      target:
        - FOREST
    itemthree:
      type: biome
      name: '&c&lDesert Biome'
      material: SAND
      lore:
        - ''
        - ''
        - ''
      invslot: 32
      target:
        - DESERT
    itemfour:
      type: biome
      name: '&c&lPlains Biome'
      material: GRASS
      lore:
        - ''
        - ''
        - ''
      invslot: 31
      target:
        - PLAINS
    itemfive:
      type: biome
      name: '&c&lJungle Biome'
      material: LOG:3
      lore:
        - ''
        - ''
        - ''
      invslot: 30
      target:
        - JUNGLE
    itemfive:
      type: biome
      name: '&c&lMesa Biome'
      material: 159:1
      lore:
        - ''
        - ''
        - ''
      invslot: 29
      target:
        - MESA
  rangegui:
    itemone:
      name: '&f1000 &7- &f5000'
      material: REDSTONE_DUST
      lore:
        - ''
        - ''
        - ''
      invslot: 2
      minrange: 1000
      maxrange: 5000
    itemtwo:
      name: '&f5000 &7- &f7500'
      material: IRON_INGOT
      lore:
        - ''
        - ''
        - ''
      invslot: 4
      minrange: 5000
      maxrange: 7500
    itemthree:
      name: '&f7500 &7- &f10000'
      material: GOLD_INGOT
      lore:
        - ''
        - ''
        - ''
      invslot: 6
      minrange: 7500
      maxrange: 10000
