default:
  world: world
  range: 10000
  teleportdelay: 5
  cooldown: 300
  cost: 0
  nopermissionmaterial: BARRIER
  insufficientfunds: '&8[&4RTP&8] &fYou do not have enough money to do that!'

messages:
  teleportationstarted: '&8[&2Wild&8] &fYou will be teleported in &b%tpdelay% &fseconds do not move!'
  teleported: '&8[&2Wild&8] &fYou have been teleported to &b%x%&f, &b%y%&f, &b%z%&f have fun!'
  alreadyteleporting: '&8[&2Wild&8] &fYou are already teleporting!'
  teleportationcancelled: '&8[&2Wild&8]&f Impending teleportation has been canceled!'
  nolocationfound: '&8[&2Wild&8] &fHey! we could not find a safe space to teleport you to :('
  oncooldown: '&8[&2Wild&8] &fHey! please wait another &b%minuets%&f minutes and &b%seconds% &fseconds before doing that'
  invalidcommand: '&8[&2Wild&8] &fInvalid command, do /randomtp help for help!'
  nopermission: '&8[&2Wild&8] &fHey! you do not have permission to do that!'
  insufficientfunds: '&8[&2Wild&8] &fYou do not have enough money to do that!'
  targetoffline: '&8[&2Wild&8] &f%player% is not online'

access:
  true: '&aYes'
  false: '&4No'

gui:
  main:
    size: 36
    name: 'Wild'
  range:
    size: 9
    name: 'Wild - Range'

guiitem:
  maingui:
    standardlore:
      - '&fClick to teleport to the %target%'
      - ''
      - '&fHas access: %access%'
      - ''
      - '&fCost: &b%cost%'

    rangeselector:
      type: rangeselector
      name: '&bRange Selector'
      material: COMPASS
      lore:
        - '&fSelect a range to teleport to'
        - '&fYour range is currently set to &b%currentmin% &8- &b%currentmax%'
      invslot: 4

    forest:
      type: biome
      name: '&a&lForest Biome'
      material: LEAVES
      invslot: 33
      target: FOREST
      targetname: 'forest'
      permission: maingui.forest

    desert:
      type: biome
      name: '&e&lDesert Biome'
      material: SAND
      invslot: 32
      target: DESERT
      targetname: 'desert'
      permission: maingui.desert

    plains:
      type: biome
      name: '&2&lPlains Biome'
      material: 3
      invslot: 30
      target: PLAINS
      targetname: 'plains'
      permission: maingui.plains

    jungle:
      type: biome
      name: '&a&lJungle Biome'
      material: LOG:3
      invslot: 29
      target: JUNGLE
      targetname: 'jungle'
      permission: maingui.jungle

    overworld:
      type: world
      name: '&2&lThe Overworld'
      material: GRASS
      invslot: 21
      target: world
      targetname: 'overworld'
      permission: maingui.overworld

    end:
      type: world
      name: '&e&lThe End'
      material: ENDER_STONE
      invslot: 23
      target: world_the_end
      targetname: 'overworld'
      permission: maingui.end

    end:
      type: world
      name: '&e&lThe End'
      material: ENDER_STONE
      invslot: 23
      target: world_nether
      targetname: 'nether'
      permission: maingui.nether


  rangegui:
    standardlore:
      - '&fClick to set range to &b%minrange% &8- &b%maxrange%'
      - ''
      - '&fHas access&7: %access%'
      - ''
      - '&fCost&7: &b%cost%'

    rangeone:
      name: '&b1000 &8- &b5000'
      material: REDSTONE
      invslot: 2
      minrange: 1000
      maxrange: 5000
      permission: rangegui.1000

    rangetwo:
      name: '&b5000 &8- &b7500'
      material: IRON_INGOT
      invslot: 4
      minrange: 5000
      maxrange: 7500
      permission: rangegui.5000

    rangethree:
      name: '&b7500 &8- &b10000'
      material: GOLD_INGOT
      invslot: 6
      minrange: 7500
      maxrange: 10000
      permission: rangegui.7500
