default:
  world: world
  range: 10000
  teleportdelay: 5
  cooldown: 300
  cost: 0
  nopermissionmaterial: BARRIER
  insufficientfunds: '&8[&4RTP&8] &fYou do not have enough money to do that!'

messages:
  teleportationstarted: '&8[&4RTP&8] &fYou will be teleported in &b%tpdelay% &fseconds do not move!'
  teleported: '&8[&4RTP&8] &fYou have been teleported to &b%x%&f, &b%y%&f, &b%z%&f have fun!'
  alreadyteleporting: '&8[&4RTP&8] &fYou are already teleporting!'
  teleportationcancelled: '&8[&4RTP&8]&f Impending teleportation has been canceled!'
  nolocationfound: '&8[&4RTP&8] &fHey! we could not find a safe space to teleport you to :('
  oncooldown: '&8[&4RTP&8] &fHey! please wait another &b%minuets%&f minutes and &b%seconds% &fseconds before doing that'
  invalidcommand: '&8[&4RTP&8] &fInvalid command, do /randomtp help for help!'
  nopermission: '&8[&4RTP&8] &fHey! you do not have permission to do that!'

gui:
  main:
    size: 36
    name: 'Wild'
  range:
    size: 9
    name: 'Wild - Range'

guiitem:
  maingui:
    standardlore:
      - ''
      - ''
      - ''

    itemone:
      type: rangeselector
      name: '&bRange Selector'
      material: COMPASS
      lore:
        - ''
        - ''
        - ''
      invslot: 13

    itemtwo:
      type: biome
      name: '&a&lForest Biome'
      material: LOG
      invslot: 33
      target: FOREST
      targetname: 'forest'
      permission: maingui.forest

    itemthree:
      type: biome
      name: '&e&lDesert Biome'
      material: SAND
      invslot: 32
      target: DESERT
      targetname: 'desert'
      permission: maingui.desert

    itemfour:
      type: biome
      name: '&2&lPlains Biome'
      material: GRASS
      invslot: 31
      target: PLAINS
      targetname: 'plains'
      permission: maingui.plains

    itemfive:
      type: biome
      name: '&a&lJungle Biome'
      material: LOG:3
      invslot: 30
      target: JUNGLE
      targetname: 'jungle'
      permission: maingui.jungle

    itemsix:
      type: biome
      name: '&6&lMesa Biome'
      material: 159:1
      invslot: 29
      target: MESA
      targetname: 'mesa'
      permission: maingui.mesa

    itemseven:
      type: world
      name: '&2&lThe Overworld'
      material: 159:1
      invslot: 29
      target: world
      targetname: 'overworld'
      permission: maingui.overworld

    itemseven:
      type: world
      name: '&e&lThe End'
      material: 159:1
      invslot: 29
      target: world
      targetname: 'overworld'
      permission: maingui.overworld


  rangegui:
    standardlore:
      - ''
      - ''
      - ''

    itemone:
      name: '&f1000 &7- &f5000'
      material: REDSTONE_DUST
      invslot: 2
      minrange: 1000
      maxrange: 5000
      permission: rangegui.1000

    itemtwo:
      name: '&f5000 &7- &f7500'
      material: IRON_INGOT
      invslot: 4
      minrange: 5000
      maxrange: 7500
      permission: rangegui.5000

    itemthree:
      name: '&f7500 &7- &f10000'
      material: GOLD_INGOT
      invslot: 6
      minrange: 7500
      maxrange: 10000
      permission: rangegui.7500
